<a href="https://colab.research.google.com/github/AnthonyM99/Seminario-Profesional/blob/master/Lab6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from __future__ import absolute_import, division, print_function, unicode_literals

# Install TensorFlow
try:
  # %tensorflow_version only works in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

import tensorflow as tf

TensorFlow 2.x selected.


In [0]:
# univariate mlp example
from numpy import array
import numpy
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Bidirectional, LSTM, Embedding

In [0]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)

In [0]:
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)

In [0]:
print (X.shape)

(6, 3)


In [0]:
XShape = numpy.reshape(X,(X.shape[0], X.shape[1],1))
XShape.shape

(6, 3, 1)

In [0]:
print(XShape)

[[[10]
  [20]
  [30]]

 [[20]
  [30]
  [40]]

 [[30]
  [40]
  [50]]

 [[40]
  [50]
  [60]]

 [[50]
  [60]
  [70]]

 [[60]
  [70]
  [80]]]


In [0]:
# define model
model = Sequential()
model.add(LSTM(4, input_shape=(n_steps,1)))
model.add(Dense(100, activation='relu', input_dim=n_steps))
model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

In [0]:
model.summary()

Model: "sequential_22"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_16 (LSTM)               (None, 4)                 96        
_________________________________________________________________
dense_25 (Dense)             (None, 100)               500       
_________________________________________________________________
dense_26 (Dense)             (None, 1)                 101       
Total params: 697
Trainable params: 697
Non-trainable params: 0
_________________________________________________________________


In [0]:
# fit model
model.fit(XShape, y, epochs=2000, verbose=0)

In [0]:
# demonstrate prediction
x_input = array([10, 20, 30])
x_input = numpy.reshape(x_input,(1, n_steps,1))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[40.010723]]
